### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by maxim-kruch** [psp2dev/raylib4Vita#2]
When I execute vita-makepkg I get an error at the end, so I looked at what went wrong a saw this: 
`In file included from core.c:133:
rlgl.h:693:14: fatal error: GLES2/gl2.h: No such file or directory
  693 |     #include <GLES2/gl2.h>              // OpenGL ES 2.0 library
      |              ^~~~~~~~~~~~~
compilation terminated.`

I checked if /usr/include/GLES2/gls2.h exists and it does. I had this result on two seperate machines, one running pop os, the other one arch.

**Comment by psxdev** [comment]
try to install https://github.com/SonicMastr/Pigs-In-A-Blanket for vitasdk you will need this installed first.

**Comment by maxim-kruch** [comment]
Thanks, that fixed the issue.
