### ISSUE TITLE
vita-makepkg does not seem to include raylib 

### ISSUE THREAD

**Issue by fleimeris** [psp2dev/raylib4Vita#3]
Hello,
I tried to install raylib for vita, but when I try to compile one of the examples I just get error:
`
raylib.h: No such file or directory
`

I've looked everywhere in vita sdk dir but I did not found raylib header and also file raylib4Vita-4.0.0-1-arm.tar.xz does not seem to include it.

Is there a way to resolve this issue ?

**Comment by psxdev** [comment]
% tar tvf raylib4Vita-4.0.0-1-arm.tar.xz
drwxr-xr-x  0 bigboss staff       0  4 feb 14:34 include/
-rw-r--r--  0 bigboss staff  215549  4 feb 14:34 include/rlgl.h
-rw-r--r--  0 bigboss staff     820  4 feb 14:34 include/rayspine.h
-rw-r--r--  0 bigboss staff   54019  4 feb 14:34 include/raymath.h
-rw-r--r--  0 bigboss staff   81301  4 feb 14:34 include/physac.h
-rw-r--r--  0 bigboss staff  112580  4 feb 14:34 include/raylib.h
drwxr-xr-x  0 bigboss staff       0  4 feb 14:34 lib/
-rw-r--r--  0 bigboss staff  672314  4 feb 14:34 lib/libraylib.a

It is included you must install pkg  raylib4Vita-4.0.0-1-arm.tar.xz in your vitasdk environment. Headers in arm-vita-eabi/include and lib on arm-vita-eabi/lib like all packages.
